theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "net"
device = "wlp3s0"
speed_up = true
speed_down = true
graph_up = true
graph_down = true
interval = 5

[[block]]
block = "battery"
interval = 10
show = "both"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max, {average}° avg"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
# format_mem = "{Mup}%"
format_mem = "{Mug}GB|{Mup}%"
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "custom"
command = "ps -eo comm,pcpu --sort=-pcpu --no-headers| head -n 1"
interval = 30

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
